[workspace]
resolver = "2"
members = ["quest", "quest-core", "quest-tests"]

[workspace.dependencies]
# workspace libraries
quest-core = { path = "./quest-core" }

# common dependencies, in alphabetical order
