[package]
name = "quest"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["blocking"] }
thiserror = "1.0.62"
url = "2.5.2"
